### ISSUE TITLE
Graphic in README.md broken on crates.io

### ISSUE THREAD

**Issue by alexschrod** [withoutboats/heck#32]
Graphic in README.md broken on crates.io; see https://crates.io/crates/heck

**Comment by jplatte** [comment]
I'm a bit surprised it even works in the readme here. I'm not sure what the best fix though, a relative link will probably only work if the image is included in the crate tarball, which it really shouldn't be. An absolute URL to raw.githubusercontent.com is also not right I think, since that domain is specifically not meant for embedding IIRC. I think I've seen some sort of "github user content CDN" before, but don't think it's official.

**Comment by jplatte** [comment]
Actually it might be that relative links are not handled as pointing into the crate tarball on crates.io. It's worth a shot I guess and definitely doesn't hurt to use a relative URL.

**Comment by jplatte** [comment]
Fixed in 0.3.3.
